"""test_ui — atomic/ui module tests (iter 17).

Run: pytest tests/test_ui.py -v
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest


def test_server_imports():
    from atomic.ui import app, Viewer, build, all_programs
    assert callable(app)
    assert callable(Viewer)
    assert callable(build)
    assert callable(all_programs)
    programs = all_programs()
    assert len(programs) >= 7, programs
    assert "gated_clock_counter" in programs


def test_program_build_and_validate():
    from atomic.ui.programs import all_programs, build
    for name in all_programs():
        prog = build(name)
        assert prog is not None, name
        prog.validate()


def test_program_compile_produces_views():
    from atomic.ui.programs import all_programs, build
    for name in all_programs():
        prog = build(name)
        patch = prog.compile("microfx")
        assert "modules" in patch, name
        assert "wires" in patch, name
        assert "views" in patch, name


def test_patch_views_autogenerated():
    from atomic.ui.programs import build
    from atomic.ui.viewer import Viewer
    prog = build("hadamard_wxyz")
    Viewer.put("hadamard_wxyz", Viewer(prog, name="hadamard_wxyz"))
    v = Viewer.get("hadamard_wxyz")
    assert len(v.view_layout) >= 4  # 4 viz_series tiles


def test_viewer_batch_produces_series():
    from atomic.ui.programs import build
    from atomic.ui.viewer import Viewer
    for name in ["hadamard_wxyz", "sine_lfo_scope", "xy_pad", "wxyz3d_demo"]:
        prog = build(name)
        v = Viewer(prog, name=name)
        snap = v.batch(20)
        assert snap["t"] == 20, name
        assert len(snap["series"]) > 0, name


def test_viewer_param_feed():
    from atomic.ui.programs import build
    from atomic.ui.viewer import Viewer
    prog = build("clock_counter")
    v = Viewer(prog, name="test_param_feed")
    Viewer.put("test_param_feed", v)
    snap0 = v.batch(5)
    assert snap0["bus"].get("cnt.acc", 0) >= 0
    v.set_param("clk", "bpm", 300.0)
    snap1 = v.batch(5)
    assert snap1["t"] == 10
    Viewer.delete("test_param_feed")


def test_viewer_tap():
    from atomic.ui.programs import build
    from atomic.ui.viewer import Viewer
    prog = build("gated_clock_counter")
    v = Viewer(prog, name="test_tap")
    Viewer.put("test_tap", v)
    v.tap()
    snap = v.batch(1)
    assert snap["t"] == 1
    Viewer.delete("test_tap")


def test_viewer_tick_once():
    from atomic.ui.programs import build
    from atomic.ui.viewer import Viewer
    prog = build("sine_lfo_scope")
    v = Viewer(prog, name="test_tick_once")
    Viewer.put("test_tick_once", v)
    for _ in range(10):
        snap = v.tick_once()
    assert snap["t"] == 10
    Viewer.delete("test_tick_once")


def test_tile_bounds_from_display():
    from atomic.tiles import Display
    d = Display(640, 480, cols=4, rows=4, frame_h=60)
    assert d.tile_w == 160
    assert d.tile_h == 105
    assert len(d.tiles) == 16
    for t in d.tiles:
        assert t.w == 160
        assert t.h == 105


def test_control_frame_schema():
    from atomic.ui.server import _control_schema
    from atomic.ui.programs import build
    from atomic.ui.viewer import Viewer
    prog = build("clock_counter")
    v = Viewer(prog, name="ctrl_test")
    schema = _control_schema(v)
    assert "params" in schema
    assert "taps" in schema
    assert len(schema["params"]) >= 1
    for p in schema["params"]:
        assert "module" in p
        assert "key" in p
        assert "min" in p
        assert "max" in p
        assert isinstance(p["value"], float)


def test_server_routes_via_testclient():
    from atomic.ui.server import create_app
    from fastapi.testclient import TestClient
    app = create_app()
    client = TestClient(app)
    with client:
        r = client.get("/api/programs")
        assert r.status_code == 200
        data = r.json()
        assert "programs" in data
        assert len(data["programs"]) >= 7


def test_batch_endpoints_all_programs():
    from atomic.ui.server import create_app
    from fastapi.testclient import TestClient
    app = create_app()
    client = TestClient(app)
    with client:
        for name in ["clock_counter", "hadamard_wxyz", "sine_lfo_scope"]:
            r = client.post(f"/api/batch/{name}", json={"ticks": 10})
            assert r.status_code == 200, f"{name}: {r.text}"
            d = r.json()
            assert d["t"] == 10, name
            assert len(d["series"]) > 0, name


def test_ws_endpoint_returns_snapshot():
    from atomic.ui.server import create_app
    from fastapi.testclient import TestClient
    app = create_app()
    client = TestClient(app)
    with client:
        r = client.post("/api/batch/hadamard_wxyz", json={"ticks": 5})
        assert r.status_code == 200
        snap = r.json()
        assert "bus" in snap
        assert "series" in snap
        assert "views" in snap
        assert len(snap["views"]) >= 4


def test_live_feed_applied():
    from atomic.ui.server import create_app
    from fastapi.testclient import TestClient
    app = create_app()
    client = TestClient(app)
    with client:
        r = client.post("/api/feed/clock_counter", json={"ticks": [5, 10], "params": {"clk": {"bpm": 200}}})
        assert r.status_code == 200
        d = r.json()
        assert d.get("ok") is True
        assert d.get("applied") == 2


def test_hadamard_wxyz_h4_rows():
    from atomic.ui.server import create_app
    from fastapi.testclient import TestClient
    app = create_app()
    client = TestClient(app)
    with client:
        r = client.post("/api/batch/hadamard_wxyz", json={"ticks": 5})
        assert r.status_code == 200
        bus = r.json()["bus"]
        assert abs(bus.get("h4.w", 0) - 4.0) < 0.01
        assert abs(bus.get("h4.x", 0) - 0.0) < 0.01
        assert abs(bus.get("h4.y", 0) - 0.0) < 0.01
        assert abs(bus.get("h4.z", 0) - 0.0) < 0.01
